services:
  streamlit:
    container_name: "exemplo_streamlit"
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
    environment:
      - STREAMLIT_SERVER_PORT=8501